import {MigrationInterface, QueryRunner} from "typeorm";

export class eventStatus1644556133872 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (0, 0, '통신on');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (0, 1, '통신off');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (1, 0, 'CAN_정상');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (1, 1, 'CAN_고장');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (2, 0, 'ONLINE');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (2, 1, 'OFFLINE');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (3, 0, '0');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (3, 1, '1');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (4, 1, '1');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (4, 0, '0');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (5, 1, 'ON');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (5, 0, 'OFF');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (6, 1, '이상');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (6, 0, '정상');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (7, 0, '정상');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (7, 1, '이상');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (8, 0, '정상');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (8, 1, '이상');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (9, 0, '점멸 종료');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (9, 1, '점멸 시작');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (10, 0, '소등 종료');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (10, 1, '소등 시작');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (11, 0, '해제');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (11, 1, '모순');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (12, 0, '수동 수등 종료');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (12, 1, '수동 소등 시작');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (13, 0, '수동 점멸 종료');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (13, 1, '수동 점멸 시작');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (14, 0, '수동 종료');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (14, 1, '수동 시작');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (15, 0, 'x');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (15, 1, '수동 버튼 누름');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (16, 0, '닫힘');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (16, 1, '열림');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (17, 0, '금지');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (17, 1, '허용');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (18, 0, '수동금지');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (18, 1, '수동허용');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (19, 0, '종료');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (19, 1, '시작');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (20, 0, '0');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (20, 1, '1');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (21, 0, '0');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (21, 1, '1');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (22, 0, '0');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (22, 1, '1');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (23, 0, 'ENABLE');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (23, 1, 'DISABLE');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (24, 0, '0');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (24, 1, '1');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (25, 0, '0');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (25, 1, '1');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (26, 0, '0');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (26, 1, '1');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (27, 0, '0');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (27, 1, '1');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (99, 0, '0');")
         await queryRunner.query("INSERT INTO event_status (event_code, event_value, event_status) VALUES (99, 1, '1');")
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
